### ISSUE TITLE
Just after installing mPDF in new server, loading same SVG file fails

### ISSUE THREAD

**Issue by RafaelLinux** [mpdf/mpdf-examples#11]
We was using mPDF without issues in a server but needed to move to a new Debian 8 server, but now mPDF is unable to show the same SVG and throws next message:
`error: Uncaught exception 'Mpdf\MpdfException' with message 'Cannot read an undeclared property Mpdf\Writer\BackgroundWriter::$gradients' in /var/www/mpdf/vendor/mpdf/mpdf/src/Strict.php:54 Stack trace: #0 /var/www/mpdf/vendor/mpdf/mpdf/src/Writer/BackgroundWriter.php(149): Mpdf\Writer\BackgroundWriter->__isset('gradients') #1 /var/www/mpdf/vendor/mpdf/mpdf/src/Writer/ResourceWriter.php(134): Mpdf\Writer\BackgroundWriter->writePatterns() #2 /var/www/mpdf/vendor/mpdf/mpdf/src/Mpdf.php(9838): Mpdf\Writer\ResourceWriter->writeResources() #3 /var/www/mpdf/vendor/mpdf/mpdf/src/Mpdf.php(2015): Mpdf\Mpdf->_enddoc() #4 /var/www/mpdf/vendor/mpdf/mpdf/src/Mpdf.php(9329): Mpdf\Mpdf->Close() #5 /var/www/mpdf/boletin_completo.php(335): Mpdf\Mpdf->Output('/var/www/mpdf/g...', 'F') #6 {main} thrown in /var/www/mpdf/vendor/mpdf/mpdf/src/Strict.php on line 54
`
What could be the problem? Any ideas?

Thank you

**Comment by finwe** [comment]
Please, use mpdf/mpdf repository to request features and/or report bugs.

---

Update to 7.1.7, this has been fixed.

**Comment by RafaelLinux** [comment]
My fault, I'm sorry. I didn't notice I was writing in the wrong forum  ;)
