### ISSUE TITLE
Bug In HTML Output When page Get's long

### ISSUE THREAD

**Issue by swartjie** [mpdf/mpdf-examples#19]
Hey Guys,

I found a possible bug in MPDF 7 where if we populate the PDF file with enough content to fit one page, whether it's one table or 7, it works without an issue, but as soon as my 3rd table for example reaches the end of the page (by which point it should create a second page), The script no longer generates the PDF file, and I am met with an error message which reads: `must precede in a table`

I did notice while playing around, if I add a page break tag right before the table, it generates the PDF fine without any issues...
From what I can see, it look's like the issue pops up as soon as the data becomes longer than 1 page, and the page is not broken by me, so it would appear to be a bug in the auto page break?

Please let me know if you need any more info from me, and/or what a possible solution to the issue might be?

**Comment by finwe** [comment]
Closing as per issue template warning. 

Feel free to open a new issue using the provided issue template with all available issue details, especially a code example to easier reproduce the issue.

**Comment by swartjie** [comment]
I am not sure why there's more required, If my html goes beyond 1 page the module breaks... How do I elaborate on that?
Do you guys need the actual code cause it's quite a lot of code...

**Comment by finwe** [comment]
Actually, the issue needs to be in the https://github.com/mpdf/mpdf repo. This repo is for the documentation. We need a reproducible code example, as small as possible (also see [MCVE](https://stackoverflow.com/help/mcve)).

Create a new issue in the repo mentioned above with such code example and all other information requested in the issue template.
