### ISSUE TITLE
MathJax's content display too thin

### ISSUE THREAD

**Issue by wuyidebh** [mpdf/mpdf-examples#24]
The example "MathJaxSample", MathJax's content displays too thin, I can't almost see anything, why? 
![ddddddddddd1](https://user-images.githubusercontent.com/31693775/121149742-7edbe080-c875-11eb-8fd5-f7e1eab13329.png)

**Comment by finwe** [comment]
Please, use mpdf/mpdf repository to request features and/or report bugs. Be sure to comply with [contributing guidelines.](https://github.com/mpdf/mpdf/blob/development/.github/CONTRIBUTING.md)
