### ISSUE TITLE
What's wrong ?

### ISSUE THREAD

**Issue by kikiminou** [mpdf/mpdf-examples#5]
I have read the readme file which says to install composer and I did. Then I ran the command 'composer install' which returned no error:

```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
$ echo $?
0
```

Then I ran the first script:

```
$ php ./example01_basic.php
PHP Warning:  require_once(/Users/xxx/Documents/www/pdf2/mpdf-examples/../../../vendor/autoload.php): failed to open stream: No such file or directory in /Users/xxx/Documents/www/pdf2/mpdf-examples/example01_basic.php on line 171

Warning: require_once(/Users/xxx/Documents/www/pdf2/mpdf-examples/../../../vendor/autoload.php): failed to open stream: No such file or directory in /Users/xxx/Documents/www/pdf2/mpdf-examples/example01_basic.php on line 171
PHP Fatal error:  require_once(): Failed opening required '/Users/xxx/Documents/www/pdf2/mpdf-examples/../../../vendor/autoload.php' (include_path='.:') in /Users/xxx/Documents/www/pdf2/mpdf-examples/example01_basic.php on line 171

Fatal error: require_once(): Failed opening required '/Users/xxx/Documents/www/pdf2/mpdf-examples/../../../vendor/autoload.php' (include_path='.:') in /Users/xxx/Documents/www/pdf2/mpdf-examples/example01_basic.php on line 171
$ echo $?
255
```

I get the same result in the browser...

Am I missing something?

**Comment by finwe** [comment]
Try current development branch, should work out of the box.

**Comment by sajinaabhayam** [comment]
Hello 

when  trying to open mpdf file  getting this error .

Warning: require(C:\xampp\htdocs\Eram\external\mpdf\vendor\composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php): failed to open stream: No such file or directory in C:\xampp\htdocs\Eram\external\mpdf\vendor\composer\autoload_real.php on line 65

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\Eram\external\mpdf\vendor\composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Eram\external\mpdf\vendor\composer\autoload_real.php on line 65

**Comment by finwe** [comment]
Update composer dependencies for mPDF.

**Comment by sajinaabhayam** [comment]
can you tell me how to update this

**Comment by finwe** [comment]
https://getcomposer.org/doc/00-intro.md

**Comment by sajinaabhayam** [comment]
ok
