### ISSUE TITLE
Images returned from tiger.php doesn't work

### ISSUE THREAD

**Issue by FeloVilches** [mpdf/mpdf-examples#8]
In `example04_images.php`, the images returned by `tiger.php` don't work.

When executing from the command line `php example04_images.php > out.pdf`, the file will contain `[X]` type of images, meaning that they failed to load.

When loading the script from the browser, it will get stuck forever loading.

**Comment by finwe** [comment]
What is your setup? mPDF version, PHP version and environment?

It is understandable that the external resource won't work via CLI - that's not a bug, it is just not prepared for that usecase.

**Comment by FeloVilches** [comment]
I posted an answer in StackOverflow with more information. It does have version and more details.

https://stackoverflow.com/questions/46480445/mpdf-images-generated-by-php-scripts

**Comment by FeloVilches** [comment]
The first line in mpdf's `CHANGELOG.md` is `mPDF 7.0.0`

**Comment by finwe** [comment]
Answered on SO.
